# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       kde5-cli-tools

# >> macros
# << macros

Summary:    Tools based on KDE Frameworks 5 to better interact with the system
Version:    5.0.0
Release:    1
Group:      System/Base
License:    GPLv2+
URL:        http://www.kde.org
Source0:    %{name}-%{version}.tar.xz
Source100:  kde5-cli-tools.yaml
Source101:  kde5-cli-tools-rpmlintrc
Requires:   kde5-filesystem
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  pkgconfig(Qt5Xml)
BuildRequires:  pkgconfig(Qt5Network)
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5Widgets)
BuildRequires:  pkgconfig(Qt5Concurrent)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(Qt5Svg)
BuildRequires:  pkgconfig(Qt5X11Extras)
BuildRequires:  pkgconfig(Qt5PrintSupport)
BuildRequires:  kde5-rpm-macros
BuildRequires:  extra-cmake-modules
BuildRequires:  kf5-kconfig-devel
BuildRequires:  kf5-kcmutils-devel
BuildRequires:  kf5-kdesu-devel
BuildRequires:  kf5-kdelibs4support-devel

%description
Tools based on KDE Frameworks 5 to better interact with the system.


%prep
%setup -q -n %{name}-%{version}/upstream

# >> setup
# << setup

%build
# >> build pre
%kde5_make
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%kde5_make_install
# << install pre

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_kde5_bindir}/kcmshell5
%{_kde5_bindir}/kde-open5
%{_kde5_bindir}/kdecp5
%{_kde5_bindir}/kdemv5
%{_kde5_bindir}/keditfiletype5
%{_kde5_bindir}/kioclient5
%{_kde5_bindir}/kmimetypefinder5
%{_kde5_bindir}/kstart5
%{_kde5_bindir}/ksvgtopng5
%{_kde5_bindir}/ktraderclient5
%{_kde5_libdir}/libkdeinit5_kcmshell5.so
%{_kde5_plugindir}/kcm_filetypes.so
%{_kde5_libexecdir}/kdeeject
%{_kde5_libexecdir}/kdesu
%{_datadir}/doc/HTML/en/kdesu
%{_datadir}/kservices5/filetypes.desktop
%{_datadir}/man/man1/kdesu.1.gz
# >> files
# << files
